server:
  port: 8080
spring:
  application:
    name: pp-food-court-service

  datasource:
    url: jdbc:mysql://localhost:3306/food_court
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: 66df918f-c69c-4cc6-9be0-8172d2a4408b
      expiration: 86400000

user-service:
  url: http://localhost:8081

notification-service:
  url: http://localhost:8082

traceability-service:
  url: http://localhost:8083
